config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'

   root 'recipes#index'

    resources :recipes, only: [:new, :create]
    
    get 'recipes/' => 'recipes#show', as: :recipe
    get 'administrator_login/', to: 'recipes#administrator_login', as: 'administrator_login'
    get 'administrator/', to: 'recipes#administrator', as: 'administrator'
    delete 'recipes/:id' => 'recipes#destroy', as: 'delete_recipe'
    get 'recipe/like/:id' => 'recipes#like', as: :like
    

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    
    has_attached_file :recipe_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "missing.png"
    validates_attachment_content_type :recipe_image, content_type: /\Aimage\/.*\Z/
    def self.allMainIngredients
        Recipe.uniq.pluck(:main_ingredient)
    end
    
    def self.allSideIngredients
        Recipe.uniq.pluck(:side_ingredient)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  def index
    @main_ingredients = Recipe.allMainIngredients
    @side_ingredients = Recipe.allSideIngredients
  end
  
  def create
    if params[:title] == "" || params[:cook_time] == "" || params[:directions] == "" || params[:main_ingredient] == "" || params[:side_ingredient] == ""
      flash[:notice] = "YOU MUST SPECIFY ALL RECIPE CRITERIA"
      redirect_to :new_recipe
    elsif params[:cook_time].to_i <= 0 || params[:cook_time].to_i > 999 || params[:cook_time].to_i % 1 != 0
      flash[:notice] = "You must enter cook time in whole minutes"
      redirect_to :new_recipe
    else
      recipe = Recipe.new()
      recipe.title = params[:title]
      recipe.cook_time = params[:cook_time]
      recipe.directions = params[:directions]
      recipe.main_ingredient = params[:main_ingredient]
      recipe.side_ingredient = params[:side_ingredient]
      recipe.recipe_image = params[:recipe_image]
      recipe.save!
      flash[:notice] = "Successfully added " + recipe.title
      redirect_to :root
    end
  end
  
  def new
    
  end
  
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = "#{@recipe.title} has been deleted"
    redirect_to administrator_path
  end

  def show
    if params[:main_ingredient] == "select" || params[:side_ingredient] == "select"
      flash[:notice] = "YOU MUST SPECIFY BOTH INGREDIENTS"
      redirect_to(:root)
      return
    end

    
    if params.has_key?(:ids)
      @ids = params[:ids].split(",")
      @recipe = Recipe.where("id NOT IN (?)", @ids)
      
    else
      @ids = []
      @recipe = Recipe
    end
    @recipe = @recipe.order(cook_time: :asc)
    @recipe = @recipe.find_by main_ingredient: params[:main_ingredient], side_ingredient: params[:side_ingredient]
    if @recipe.nil? and !@ids.empty?
      flash[:notice] = "There are no more recipes for these ingredients"
      redirect_to(:root)
      return
    elsif @recipe.nil?

      flash[:notice] = "There is no recipe with these ingredients"
      redirect_to(:root)
      return
    end
    
    @ids.push @recipe.id
    
  end
  
  def administrator_login
    
  end
  
  def administrator
    @recipes = Recipe.all.each
  end
  
  def like
    @recipe = Recipe.find(params[:id])
    
    likes = @recipe.likes || 0
    @recipe.likes = likes + 1
    @recipe.save!
    flash[:notice] = "Thanks: #{@recipe.likes} total likes"
    @ids = params[:ids].split(",")
    @ids.delete @recipe.id
    params[:ids] = @ids.join(",")
    redirect_to recipe_path :params => params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Recipe Finder!?
    = stylesheet_link_tag 'main', 'media' => 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'google-fonts', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag :all
    = csrf_meta_tags

  %body
    =image_tag "Banner.jpg"
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/recipes/administrator.html.haml
-#  This file is app/views/recipes/administrator.html.haml
%h1 Administrator Portal
%h2 Delete a Recipe
%table#recipes
  %thead
    %tr
      %th Action
      %th Title
      %th Cook Time
      %th Directions
      %th Main Ingredient
      %th Side Ingredient
      %th Created
      %th Last Updated
      %th Likes
      %th Image Name
      %th Image Type
      %th Image Size
      %th Image Last Updated
  %tbody
    - @recipes.each do |recipe|
      %tr
        %td= button_to 'Delete', delete_recipe_path(recipe.id), :method => :delete, :confirm => 'Are you sure?'
        %td= recipe.title
        %td= recipe.cook_time
        %td= recipe.directions
        %td= recipe.main_ingredient
        %td= recipe.side_ingredient
        %td= recipe.created_at
        %td= recipe.updated_at
        %td= recipe.likes
        %td= recipe.recipe_image_file_name
        %td= recipe.recipe_image_content_type
        %td= recipe.recipe_image_file_size
        %td= recipe.recipe_image_updated_at
%table
  %tr
    %td
      =form_tag :root, :method => :get do
        %input{:type=>"submit", :value => "Exit"}

app/views/recipes/administrator_login.html.haml
-#  This file is app/views/recipes/administrator_login.html.haml
%h1 Administrator Login
=form_tag administrator_path, :method => :get do
  %table#admin_login_form{:style=>"width: 480px"}
    %tr
      %td
        Username
      %td
        %input#title{:name => "username", :type => "text"}
    %tr
      %td
        Password
      %td
        %input#title{:name => "password", :type => "password"}
    %tr
      %td
      %td
        %input{:type => "submit", :value => "Login"}
%table
  %tr
    %td
      =form_tag :root, :method => :get do
        %input{:type=>"submit", :value => "Back"}

app/views/recipes/index.html.haml
-#  This file is app/views/recipes/index.html.haml
%h1 Search Recipes
=form_tag recipe_path, :method => :get do
  %table#ingredients_form{:style=>"width: 480px"}
    %tr
      %td
        Main Ingredient
      %td
        %select#main_ingredient{:name => "main_ingredient", :required => "true"}
          %option{:value => "select"} Select
          =options_for_select(@main_ingredients)
    %tr
      %td
        Side Ingredient
      %td
        %select#side_ingredient{:name => "side_ingredient", :required => "true"}
          %option{:value => "select"} Select
          =options_for_select(@side_ingredients)
    %tr
      %td
      %td
        %input{:type => "submit", :value => "Submit"}
%table
  %tr
    %td
      = button_to 'Add Recipe', :new_recipe, :method => :get
    %td
      = button_to 'Administrator Login', :administrator_login, :method => :get

app/views/recipes/new.html.haml
-#  This file is app/views/recipes/new.html.haml
%h1 Submit New Recipes
=form_tag recipes_path ,multipart: true do
  %table#ingredients_form{:style=>"width: 480px"}
    %tr
      %td
        Title
      %td
        %input#title{:name => "title", :type => "text"}
    %tr
      %td
        Cook Time (minutes)
      %td
        %input#cook_time{:name => "cook_time", :type => "number"}
    %tr
      %td
        Directions
      %td
        %textarea#directions{:name => "directions"}
          :preserve
    %tr
      %td
        Main Ingredient
      %td
        %input#main_ingredient{:name => "main_ingredient", :type => "text"}
    %tr
      %td
        Side Ingredient
      %td
        %input#side_ingredient{:name => "side_ingredient", :type => "text"}
    %tr
      %td
        Image
      %td
        = file_field_tag :recipe_image
    %tr
      %td
      %td
        %input{:type => "submit", :value => "Submit"}
%table
  %tr
    %td
      =form_tag :root, :method => :get do
        %input{:type=>"submit", :value => "Back"}

app/views/recipes/show.html.haml
-#  This file is app/views/recipes/show.html.haml
%table{:style=>"width: 480px"}
    %tr
        %td
            Title
        %td= @recipe.title
    %tr
        %td
            Cook Time
        %td= @recipe.cook_time
    %tr
        %td
            Main Ingredient
        %td= @recipe.main_ingredient
    %tr
        %td
            Side Ingredient
        %td= @recipe.side_ingredient
    %tr
        %td
            Directions
        %td
            = @recipe.directions
    %tr
        %td
            Image
        %td
            = image_tag @recipe.recipe_image.url

%br
%br
%table{:style=>"width: 480px"}
    %tr
        %td{:colspan => 2}
            Like this recipe?
    %tr
        %td
            =form_tag like_path(@recipe.id), :method => :get do
                %input{:type=>"hidden", :value=>params[:main_ingredient], :name=>"main_ingredient"}
                %input{:type=>"hidden", :value=>params[:side_ingredient], :name=>"side_ingredient"}
                %input{:type=>"hidden", :value=>"#{@ids.join(",")}", :name=>"ids"}
                %input{:type=>"submit", :value=>"Yes"}
        %td
            =form_tag recipe_path, :method => :get do
                %input{:type=>"hidden", :value=>params[:main_ingredient], :name=>"main_ingredient"}
                %input{:type=>"hidden", :value=>params[:side_ingredient], :name=>"side_ingredient"}
                %input{:type=>"hidden", :value=>"#{@ids.join(",")}", :name=>"ids"}
                %input{:type=>"submit", :value=>"No Find Another"}
        %td
            =button_to 'Back', :root, :method => :get
            